Edge Case Test Coverage
project-slippi/slippi-js pull request #57
Opened 2021-02-15 23:48 UTC by OGoodness

Added Slippi files and tests cases. 

Slippi files contain the following:
- Bowser Side Special and variations
- Falcon Hug
- Ganon Hug
- Kirby Swallow/Release/Breakout
- Yoshi Egg Lay

2021-02-16 00:01 UTC, vinceau requested changes

2021-02-16 00:01 UTC, vinceau commented on test/stats.spec.ts
> +      stats.conversions.map( conversion => {
```suggestion
      stats.conversions.forEach( conversion => {
```
Minor pet-peeve, can you replace all the `map` with `forEach`? In these cases we don't really care about the actual mapping of one array into another array, rather we just care about iterating through each value.

2021-02-16 00:05 UTC, vinceau commented on test/stats.spec.ts
> +      stats.conversions.map( conversion => {
You'd need to repeat this change for all the other `.map` instances btw. Not just this one instance.

2021-02-17 03:18 UTC, NikhilNarayana commented on src/stats/common.ts
> +    state !== State.BARREL_CANNON_WAIT
why not just have `COMMAND_GRAB_RANGE2_END` go up to `0x152`?

2021-02-17 03:58 UTC, vinceau requested changes

2021-02-17 03:58 UTC, vinceau commented on src/stats/common.ts
> +  BARREL_CANNON_WAIT = 0x153,
Did you mean to explicitly ignore the BarrelWait or BarrelCannonWait?

```suggestion
  BARREL_WAIT = 0x125,
```

2021-02-17 03:58 UTC, vinceau commented on src/stats/common.ts
> +  COMMAND_GRAB_RANGE2_END = 0x153,
As Nikki mentioned already, why set the end range to `0x153` and then explicitly ignore `0x153`? Why not just set the end range to `0x152`?

```suggestion
  COMMAND_GRAB_RANGE2_END = 0x152,
```

2021-02-17 22:39 UTC, vinceau approved these changes

2021-02-17 22:40 UTC, merged